### ISSUE TITLE
sso 成功后如何分享微博

### ISSUE THREAD

**Issue by jackie19** [iVanPan/cordova_weibo#1]
请问授权成功后，想要发微博应该怎么做

**Comment by iVanPan** [comment]
@jackie19 看一下这个微博接口 http://open.weibo.com/wiki/2/statuses/update
你也可以自己修改我的代码，调用sdk来发微博

**Comment by jackie19** [comment]
成功解决，感谢热心回答

**Comment by Chaunjie** [comment]
这个分享好像不能图片和链接一同分享吧

**Comment by Chaunjie** [comment]
this.shareToWeibo = function () {
    var args = {};
    args.url = "http://www.baidu.com";
    args.title = "Baidu";
    args.description = "This is Baidu";
    args.imageUrl = "https://www.baidu.com/img/bdlogo.png";//if you don't have imageUrl,for android http://www.sinaimg.cn/blog/developer/wiki/LOGO_64x64.png will be the defualt one
    args.defaultText = "";
    YCWeibo.shareToWeibo(function () {
      alert("share success");
    }, function (failReason) {
      alert(failReason);
    }, args);
  };
好像没有一个是图片字段以及分享到输入框的字段

**Comment by Chaunjie** [comment]
楼主在分享的时候少了图片压缩操作，不然图片太大就换不起来微博app，建议楼主加上，还有就是缺少分享媒体的也建议加上，我个人已经加上

**Comment by iVanPan** [comment]
@xudao520  好的，谢谢！

**Comment by ViPenn** [comment]
@xudao520  分享链接 没有图片你是怎么改的？

**Comment by Chaunjie** [comment]
没有图片的我没考虑我默认是给了一张图片的

**Comment by ViPenn** [comment]
@xudao520  我的意思是 我分享的是链接和图片，但是图片文字都不显示你是怎么修改的？

**Comment by Chaunjie** [comment]
这个我没做修改，我只是添加了一个多媒体的分享，等待你修改。。。
