### ISSUE TITLE
为什么ionic build 和run的时候有这么多warning

### ISSUE THREAD

**Issue by seasonstar** [iVanPan/cordova_weibo#10]
按照步骤安装插件，安装后 ionic build 发现很多warning。不过没有影响插件正常使用。

取一部分贴上来：
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.0-7A220/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-gccnypuzcgdpbcbxkksbfqqsmdwa/WeiboSDK-Prefix.pch.pch: No object file for requested architecture
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSData
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSURLConnection
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSMutableData
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSURLRequest
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSCachedURLResponse
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSError
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSOperationQueue
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSMutableDictionary
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSHTTPCookie
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSMutableURLRequest
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSURLResponse
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSMutableArray
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBHttpRequest.o):
warning: Could not resolve external type c:objc(cs)NSHTTPCookieStorage
while processing /Users/yaoxingtang/maybi/maybi-ionic/platforms/ios/maybi-ionic/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKBasicWebViewController.o):

绝大多数都是libWeiboSDK.a的warning，下载最新的WEIBO IOS SDK 也没有得到解决。
请问有好的解决办法吗？

**Comment by iVanPan** [comment]
@seasonstar  这是SDK的问题 要等SDK更新才行

**Comment by iVanPan** [comment]
@seasonstar  有warning是因为 SDK 没有适配 Xcode 7的工程 详情可以看[这里](https://github.com/ChenYilong/iOS9AdaptationTips#xcode7-%E5%9C%A8-debug-%E7%8A%B6%E6%80%81%E4%B8%8B%E4%B9%9F%E7%94%9F%E6%88%90-dsym-%E6%96%87%E4%BB%B6%E5%BC%95%E8%B5%B7%E7%9A%84%E8%AD%A6%E5%91%8A) 不过不影响使用

**Comment by seasonstar** [comment]
@iVanPan 谢谢，真是醉了，其他信息都被刷下来了
