### ISSUE TITLE
微博分享的时候imageUrl 设置无效

### ISSUE THREAD

**Issue by luxp** [iVanPan/cordova_weibo#11]
我的手机上装的微博版本是 5.6.0
在安装了插件之后，测试了一下示例的代码，发现在分享链接时 imageUrl 设置无效，分享出去的不是带有图片的链接，只是一个简单的链接

**Comment by iVanPan** [comment]
@luxp 
<img width="980" alt="2015-12-10 22 29 11" src="https://cloud.githubusercontent.com/assets/1687276/11717765/7da3b394-9f8d-11e5-8a86-2c4ada3c0d8a.png">  您可以在[这里](https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20FAQ.md)查看 微博SDK常见的一些问题

**Comment by luxp** [comment]
@iVanPan 多谢，明白了
