### ISSUE TITLE
xcode  Release 编译错误

### ISSUE THREAD

**Issue by xml777** [iVanPan/cordova_weibo#13]
提示:
file is universal (4 slices) but does not contain a(n) armv7s slice 。。。
libWeiboSDK.a' for architecture armv7s

请问有没有解决办法

**Comment by iVanPan** [comment]
应该是微博sdk的问题，你去Weibo sdk的Github下面问问

—

**Comment by xml777** [comment]
嗯，我去下一个新的试试 。非常感谢
