### ISSUE TITLE
谢谢博主无私奉献，请问用您这个插件的话，iOS下需要依赖Info.plist -> URL Schemes吗？

### ISSUE THREAD

**Issue by berserker001** [iVanPan/cordova_weibo#14]
安装插件后，Info.plist -> URL Schemes节点下是没有出现关于微博相关的配置。

**Comment by iVanPan** [comment]
@berserker001  感谢反馈，请问你的Xcode版本 和Cordova版本是多少？ 
<img width="588" alt="2016-01-21 10 14 42" src="https://cloud.githubusercontent.com/assets/1687276/12469592/f732fade-c027-11e5-81b8-fdd724ac7149.png"> 我在最新的版本(Xcode 也是最新的)下面都没有问题，安装插件以后也会在URL Schemes节点下出现关于微博相关的配置

**Comment by berserker001** [comment]
xcode version 7.2(7C68)
cordova version 5.4.1

**Comment by berserker001** [comment]
用您开源的Cordova_QQ，通过cordova plugin add 指令安装后，Info.plist -> URL Schemes里是有相关配置的。

**Comment by berserker001** [comment]
![a54b5374-d0d3-4d5c-b425-38f38484f631](https://cloud.githubusercontent.com/assets/3414507/12471958/c590d0bc-c03d-11e5-8a42-c9804f27a867.png)
如APP ID无误，是否这样配置就可以了？

**Comment by iVanPan** [comment]
@berserker001  可以这样手动添加，你新建一个测试工程也是这样吗？ 是通过git 装的还是 npm 装的？ cordova-ios 的版本是多少？ 以前在旧版本的cordova-ios 工程上面是有一个bug的，只要有一个插件添加过URL Schemes 第二个就不能自动添加了，需要手动添加才行！
