### ISSUE TITLE
点击微博登陆->登陆列表，点击用户登陆，闪到主页，马上又闪回用户列表了

### ISSUE THREAD

**Issue by dajavu** [iVanPan/cordova_weibo#17]
点击微博登陆->登陆列表，点击用户登陆，闪到主页，马上又闪回用户列表了，我cordova Android平台版本是5.1.1的，我手机是4.4，是版本问题么？

**Comment by iVanPan** [comment]
@PasDajavu  有log嘛？ android 签名正确吗？

**Comment by dajavu** [comment]
我刚刚看了您回答的其他，搞定了，是签名的问题，您的这个插件真的是帮我大忙了，十分感谢
