### ISSUE TITLE
分享成功了，但是还有问题想问一下

### ISSUE THREAD

**Issue by giantss** [iVanPan/cordova_weibo#19]
分享出去的的网页就一个链接啊，图和文字不能显示出来吗

**Comment by iVanPan** [comment]
https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20FAQ.md

**Comment by giantss** [comment]
谢谢，再问一句如果开通了LinkCard，插件需要修改吗
