### ISSUE TITLE
sharefail

### ISSUE THREAD

**Issue by duchao1990** [iVanPan/cordova_weibo#2]
点击弹出框为sharefail,你的qq我已经分享成功了,但是weibo,同样的方法是分享失败是怎么回事呀

**Comment by iVanPan** [comment]
@duchao1990  请问是iOS 9吗 ？还是Android？

**Comment by duchao1990** [comment]
是android的

**Comment by duchao1990** [comment]
@iVanPan 是安卓版的

**Comment by iVanPan** [comment]
@duchao1990  感谢反馈 我会抽时间尽快修复的，能否麻烦你 把你系统信息给我一下

**Comment by iVanPan** [comment]
@duchao1990  你的apk 签名正确吗？

**Comment by duchao1990** [comment]
@iVanPan 谢谢你,你提醒了我.我发现我申请了App ID之后,以前填写的签名什么的没保存了,现在可以了.谢谢
