### ISSUE TITLE
应用已经审核通过，DEBUG版本正常，签名之后，登陆授权提示“文件不存在（C8998）”错误

### ISSUE THREAD

**Issue by calcyu** [iVanPan/cordova_weibo#21]
应用已经审核通过，DEBUG版本正常，签名之后，登陆授权提示“文件不存在（C8998）”的错误
使用的就是你提供的实例文件，什么都没有改，唯一不同就是一个是DEBUG版本，一个是签名版本

**Comment by iVanPan** [comment]
@calcyu  检查一下你的回调URL是否正确,你可以Google一下 这个[问题](https://www.google.co.jp/search?q=%E6%96%87%E4%BB%B6%E4%B8%8D%E5%AD%98%E5%9C%A8%EF%BC%88C8998%EF%BC%89)很常见的

**Comment by calcyu** [comment]
@iVanPan 谢谢已解决是 MD5的问题，同一个包路径，DEBUG和RELEASE的MD5不同引起的
