### ISSUE TITLE
IOS9.3下用微博登录，信息获取成功后，没按确认自动跳回APP了，怎么解决？

### ISSUE THREAD

**Issue by shiningwhite** [iVanPan/cordova_weibo#23]
你好，
Cordova版本 6.3.0
Xcode版本 7.3.1

IOS9.3下用微博App登录，信息获取成功后，没按确认就自动跳回APP了，默认已经授权了，怎么解决？
谢谢～

**Comment by iVanPan** [comment]
@shiningwhite  调用一下登出的方法，如果不行就删除微博的授权。

**Comment by shiningwhite** [comment]
@iVanPan 确实是没有登出，登出以后就好了，之前一直在测试登录，微博是不会重复授权的，谢谢啦～

**Comment by giantss** [comment]
我也遇到同样的问题，之前都是可以的，昨天测试说不行了

**Comment by giantss** [comment]
![cf78d3d9-9938-abe1-f641-75072d05025b](https://cloud.githubusercontent.com/assets/13778798/18407465/ad086fb0-7743-11e6-9ea9-9963d24256c3.png)
我用gapDebug调试 请求用户信息的接口报了上图错误

**Comment by giantss** [comment]
@iVanPan
