### ISSUE TITLE
C8998 文件找不到

### ISSUE THREAD

**Issue by gzfgeh** [iVanPan/cordova_weibo#24]
1、包名签名一致，其中不包含空格和不一样字符
2、微博平台设置 授权回调地址和xml中配置一致https://api.weibo.com/oauth2/default.html
3、安卓手机上面报文件找不到C8998

**Comment by iVanPan** [comment]
https://github.com/sinaweibosdk/weibo_android_sdk/issues/165 看一下新浪官方issue， 我这边只是微博SDK的一个wrapper而已 @gzfgeh

**Comment by iVanPan** [comment]
@gzfgeh  你重新检查一下 一般签名不正确或事回调地址不正确 会造成这个问题

**Comment by gzfgeh** [comment]
这两个我确认两天了，确实没问题，然后我想知道  微博平台上面的 安全域名 和这个有关系吗？

**Comment by iVanPan** [comment]
@gzfgeh  我以前用的时候 没有设置过，不过我Google了一下这个问题，貌似有人设置这个安全域名后也有这个问题。
