### ISSUE TITLE
插件在ios10无法运行

### ISSUE THREAD

**Issue by rehiy** [iVanPan/cordova_weibo#25]
IOS 10 ／xCode 8.1 ／Cordova 6 编译之后无法调起weibo分享。控制台输入如下。

THREAD WARNING: ['YCWeibo'] took '202.842773' ms. Plugin should use a background thread.

**Comment by iVanPan** [comment]
@anrip  插件里面的demo 能不能跑通？ 我测试了一下可以正常分享 也是 iOS 10，Xcode 8.1

**Comment by rehiy** [comment]
我测试出来了，是因为缩略图太大造成的
 
 
------------------ 原始邮件 ------------------
发件人: "Van"; 
发送时间: 2016年11月27日(星期天) 中午11:44
收件人: "iVanPan/cordova_weibo"; 
抄送: "若海"; "Mention"; 
主题: Re: [iVanPan/cordova_weibo] 插件在ios10无法运行 (#25)

 

@anrip  插件里面的demo 能不能跑通？ 我测试了一下可以正常分享 也是 iOS 10，Xcode 8.1

**Comment by iVanPan** [comment]
@anrip  好的 SDK对图片大小，URL的长度都有限制的
