### ISSUE TITLE
调用分享方法无反应

### ISSUE THREAD

**Issue by wzzts** [iVanPan/cordova_weibo#26]
调用分享方法无反应，error也没有，但是检测客户端是否安装跟sso登录都是有用的，实在是不知道哪里有问题了...

**Comment by iVanPan** [comment]
图片太大 或是url长度过长可能会造成这个问题 @wzzts

**Comment by wzzts** [comment]
感谢。 已解决，是图片太大的问题。

**Comment by wzzts** [comment]
感谢。 已解决，是图片太大的问题。@iVanPan
