### ISSUE TITLE
最新IOS要求使用https

### ISSUE THREAD

**Issue by geminili** [iVanPan/cordova_weibo#27]
求作者更新一个最新的版本，因为最新的IOS强制要求使用https，目前这个版本app store 审核没法通过

**Comment by iVanPan** [comment]
@geminili  微博官方并没有更新SDK，目前给出的方案是这样的
<img width="973" alt="2016-12-20 09 24 04" src="https://cloud.githubusercontent.com/assets/1687276/21334983/497dbdc2-c696-11e6-9539-f2ccff858887.png">
，你自己修改一下Xcode工程配置就行了
