### ISSUE TITLE
ionic中使用cordova_weibo插件，为什么回调函数没有被触发

### ISSUE THREAD

**Issue by tongtongchen0** [iVanPan/cordova_weibo#28]
使用ionic+cordova创建的APP中加入cordova_weibo插件，使用checkClientInstalled判断客户端是否安装，可是回调函数使用没有触发，什么情况？

**Comment by iVanPan** [comment]
@tongtongchen0  demo可以跑嘛？ 你提供的信息太少，我也不清楚。

**Comment by tongtongchen0** [comment]
找到问题了，是我在APP中使用了Cordova-plugin-crosswork-webviwe插件，替换了内置的ebview，
在执行checkClientInstalled时，提示：Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343，移除Cordova-plugin-crosswork-webviwe插件之后，使用默认webview，就可以正常回调了！
       对于Corsswork的这个问题有什么解决办法吗？

**Comment by iVanPan** [comment]
@tongtongchen0 这个只是warning吧，执行大于了50ms，并不一定是主因，我以前用没有这个问题

**Comment by tongtongchen0** [comment]
也是在crosswalk下使用的吗？把crosswalk移除之后，再使用就正常了

**Comment by iVanPan** [comment]
我以前也用过crosswalk 并没有什么问题，当然已经一年多没有写过Cordova，crosswalk发展到什么地步了我也不是很清楚，我查了一下这个warning，Google上面有很多，你可以搜搜看，或许能找到解决方案

**Comment by tongtongchen0** [comment]
我是最近采用的crosswalk，已经遇到了几个没法解决的问题了～～～～～
