### ISSUE TITLE
分享微博时候安卓没有反应，无法打开微博

### ISSUE THREAD

**Issue by wysteria** [iVanPan/cordova_weibo#29]
01-16 19:59:03.445 8625-9564/com.binary.ggj W/PluginManager: THREAD WARNING: exec() call to YCWeibo.shareToWeibo blocked the main thread for 42ms. Plugin should use CordovaInterface.getThreadPool().
01-16 19:59:03.450 8625-8716/com.binary.ggj I/System.out: [CDS]rx timeout:0
01-16 19:59:03.485 8625-8625/com.binary.ggj E/chromium: [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
01-16 19:59:03.520 8625-8625/com.binary.ggj D/CordovaActivity: Paused the activity.
01-16 19:59:03.520 8625-8625/com.binary.ggj I/JPushPlugin: ----------------  onPause
01-16 19:59:03.610 8625-12421/com.binary.ggj I/System: core_booster, getBoosterConfig = false
01-16 19:59:03.610 8625-12421/com.binary.ggj I/System.out: [socket][4] connection /180.149.135.176:443;LocalPort=42794(25000)
01-16 19:59:03.610 8625-12421/com.binary.ggj I/System.out: [CDS]connect[/180.149.135.176:443] tm:25
01-16 19:59:03.660 8625-12421/com.binary.ggj I/System.out: [socket][/192.168.1.25:42794] connected
01-16 19:59:03.660 8625-12421/com.binary.ggj I/System.out: [CDS]rx timeout:20000
01-16 19:59:03.660 8625-12421/com.binary.ggj I/System: core_booster, getBoosterConfig = false
01-16 19:59:03.665 8625-8625/com.binary.ggj D/HwCust: Create obj success use class android.app.HwCustApplicationPackageManagerImpl
01-16 19:59:03.725 8625-8625/com.binary.ggj D/CordovaActivity: Incoming Result. Request code = 765
01-16 19:59:03.725 8625-8625/com.binary.ggj W/CordovaInterfaceImpl: Got an activity result, but no plugin was registered to receive it.
01-16 19:59:03.725 8625-8625/com.binary.ggj D/CordovaActivity: Resumed the activity.
01-16 19:59:03.725 8625-8625/com.binary.ggj I/JPushPlugin: ---------------- onResume-null-null
01-16 19:59:03.925 8625-12421/com.binary.ggj I/System: core_booster, getBoosterConfig = false
01-16 19:59:03.925 8625-12421/com.binary.ggj I/System.out: [socket][5] connection /180.149.135.176:443;LocalPort=53845(25000)
01-16 19:59:03.925 8625-12421/com.binary.ggj I/System.out: [CDS]connect[/180.149.135.176:443] tm:25
01-16 19:59:03.975 8625-12421/com.binary.ggj I/System.out: [socket][/192.168.1.25:53845] connected
01-16 19:59:03.975 8625-12421/com.binary.ggj I/System.out: [CDS]rx timeout:20000
01-16 19:59:03.975 8625-12421/com.binary.ggj I/System: core_booster, getBoosterConfig = false
android sdk 22

**Comment by wysteria** [comment]
签名问题，已解决

**Comment by pedoc** [comment]
@wysteria 你好，能否详细说明一下怎么解决的，遇到了类似的问题
