### ISSUE TITLE
心情温度计 was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by hcxiong** [iVanPan/cordova_weibo#3]
测试发现iphone6plus有此bug，使用微博登陆直接闪退:
心情温度计 was compiled with optimization - stepping may behave oddly; variables may not be available.
WBSDKJSONKit.m:2870后面 wbsdkjk_encode_add_atom_to_buffer ---> EXC_BAD_ACCESS(code=1,address=.....)

**Comment by iVanPan** [comment]
@hcxiong  是iOS 9 嘛？目前微博 iOS 版本的 SDK 在iOS 9 上面有一堆问题，可以查看https://github.com/sinaweibosdk/weibo_ios_sdk/issues 你可以更新SDK试试。我会在国庆过后更新这个插件一个版本

**Comment by iVanPan** [comment]
@hcxiong  @chengrenz 已经更新了一个版本！ 更新了 Android 和 iOS 的SDK 添加了 对iOS9 的支持！欢迎使用测试
