### ISSUE TITLE
首先声明已经分享成功，是用户体验上的提升

### ISSUE THREAD

**Issue by xupx1993** [iVanPan/cordova_weibo#30]
现在分享出去的情况是微博内容默认为空，发布按钮为不可用状态，在args里有个defaultText的值，这个是不是设置默认内容的呢？但是设置了没有起作用，插件提供这个功能吗？

**Comment by iVanPan** [comment]
@xupx1993  defaultText 这个是针对 Android 的。插件只是针对微博SDK的封装而已，微博万年不更新SDK，各种问题无动于衷，我以前没有这个问题，现在就这样吧
