### ISSUE TITLE
iOS 开发环境下，分享成功了，但是显示画面链接没有带入，安卓下没有这种问题

### ISSUE THREAD

**Issue by MyNameIsInherit** [iVanPan/cordova_weibo#31]
Before submitting issues ...

- 确保你的 App 在[微博开放平台](http://open.weibo.com/)已审核通过.
- 如果是 Android 平台请确保你的apk签名是正确的.
- 请确认demo已测试通过.
- 请先搜索相关的issues,看是否同样的问题已经有解决方案了.
- 发生授权出错的情况，请前先去微博开发者平台咨询，也可查看微博开发的[常见问题](https://github.com/sinaweibosdk/weibo_ios_sdk/blob/master/FAQ.md).

当你提交 issues 的时候, 请提供以下信息来帮助开发者更好的修复Bug:

- 开发环境: 插件版本, Cordova版本, Xcode版本.
- 如果出现错误，希望提供Xcode或Android Studio的错误日志.
- 如果有其他额外的信息，也希望可以提供一下，帮助我们更快的定位问题.

**Comment by MyNameIsInherit** [comment]
![111wechatimg1](https://cloud.githubusercontent.com/assets/13914360/23649469/949d020e-0359-11e7-90b5-44e87e85eddc.jpeg)
![2222](https://cloud.githubusercontent.com/assets/13914360/23649472/960b786e-0359-11e7-808e-910514fe5e99.jpeg)
![333](https://cloud.githubusercontent.com/assets/13914360/23649476/9a1233b2-0359-11e7-8848-45fcba7a8e97.png)

**Comment by MyNameIsInherit** [comment]
安卓上显示链接，苹果上没有网页链接，怎么回事？？

**Comment by iVanPan** [comment]
@MyNameIsInherit  我测试了 一下并没有这个问题，你的链接太长了可能会有问题，你提供信息太少 我也看不出来

**Comment by MyNameIsInherit** [comment]
@iVanPan  http://www.XXXXX.com/?m=module_kaiy_topic.ui_portal.index&tag=&category=&account=&filter=49&share=1
算长吗？

**Comment by MyNameIsInherit** [comment]
<img width="900" alt="2017-03-07 5 39 30" src="https://cloud.githubusercontent.com/assets/13914360/23650451/1a50f45c-035d-11e7-9ea6-a16fb5ef3282.png">

**Comment by MyNameIsInherit** [comment]
问题是安卓下没问题，iOS下不显示链接？ @iVanPan

**Comment by iVanPan** [comment]
@MyNameIsInherit  我只是说可能， 在Cordova 6.5, iOS 10.2.1  最新的微博客户端下做测试并没有重现你的问题

**Comment by MyNameIsInherit** [comment]
@iVanPan  当前我是cordova 6.4.0.
