### ISSUE TITLE
安卓无法切换账号

### ISSUE THREAD

**Issue by chenkun24** [iVanPan/cordova_weibo#33]
安卓上登录过一次微博后，退出再次登录，跳转到微博应用后立即返回（使用当前的账号授权登录），无法切换账号。

**Comment by iVanPan** [comment]
有调用logout吗？ 调用一下在重新登陆啊 @chenkun24

**Comment by chenkun24** [comment]
有调用的，可以正常退出。iOS基本没问题，就是安卓有问题。你那边能够重现吗？

**Comment by iVanPan** [comment]
@chenkun24  我并没有 Android 手机，但是看了一下逻辑并没有问题，登出的时候会清除用户信息的，你 Android 的版本是多少？ 可能是版本问题

**Comment by chenkun24** [comment]
安卓版本5.1.1，微博版本7.2.0，感觉不像安卓的问题。

**Comment by iVanPan** [comment]
@chenkun24  我清除信息调用的是微博提供的方法，现在没有手机测试不了，要等有手机了才行

**Comment by iVanPan** [comment]
@chenkun24  我重写了这个插件， Android 在 5.1.1 微博7.4.0 上面做过测试没有你这个问题了，你可以试一下

**Comment by chenkun24** [comment]
试了下应该是微博自己的问题。当已经登录了多个账号，则要求微博登录时允许切换；如果只登录了一个账号，则直接返回了。
其他还有一些问题也可能和系统和微博内部框架相关的，比如如果手机未打开微博，则以新页面的形式要求登录微博；如果手机已打开微博，则会跳转到客户端要求登录微博。
