### ISSUE TITLE
couldn't find "libweibosdkcore.so"

### ISSUE THREAD

**Issue by lizhug** [iVanPan/cordova_weibo#38]
最新官网版本

Process: com.zunars.app, PID: 23446
                                                                java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zunars.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zunars.app-1/lib/arm64, /data/app/com.zunars.app-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libweibosdkcore.so"

**Comment by lizhug** [comment]
我感觉libs里面应该要有libweibosdkcore.so这个文件的吧,实测在libs中添加libwebosdk.so后就可以了，但是是调用网页版本，而不是唤起客户端，得看一下

**Comment by iVanPan** [comment]
你可以手动更新一下sdk，Android 新版本的 sdk 问题比较多，但是老的可能六月份就用不了了，唤不起客户端可能是应用没有注册到微博，你可以看一下新版本的demo，跑一下测试一下

**Comment by iVanPan** [comment]
@lizhug  试一下新的版本 应该已经修复了

**Comment by lizhug** [comment]
这个问题已经修复，在测试过程中还遇到了一个问题，发送微博不成功。因为使用的开放平台里面网页的那个appid，不是移动应用，所以还需要再测一下，过段时间我反馈

**Comment by lizhug** [comment]
确实是因为上面说的那个原因，已经搞定，thx
