### ISSUE TITLE
想请问

### ISSUE THREAD

**Issue by roy1ee** [iVanPan/cordova_weibo#39]
当进入login with weibo页面时，按了ok键，但是只是中间出现旋转logging in...，就没反应了，不过我的App还没经过审刻，请问这是正常的吗？

**Comment by iVanPan** [comment]
是不是审核的问题，我不清楚，你要问一下 新浪开发人员，如果是 Android 的话 确保你的 签名是正确的

**Comment by roy1ee** [comment]
对，我的是android的，想请问签名是从这里下载
https://github.com/mobileresearch/weibo_android_sdk/blob/master/app_signatures.apk
到手机，然后输入Android名包(Package Name)，然后产生的对吗？

**Comment by iVanPan** [comment]
android 签名文件是你自己生成的啊，这个工具只是为了校验你的应用 安装完签完名的应用，在用这个工具生成一个值，填在微博开放平台上面。看一下微博开放平台的流程

**Comment by roy1ee** [comment]
好的，谢谢你。

**Comment by roy1ee** [comment]
还有个问题，当我使用WeiboSDK.ssoLogin时，会出现WeiboSDK is not defined，不过用YCWeibo.ssoLogin却可以正常使用，想请教是不是哪里出错了？

**Comment by iVanPan** [comment]
@roy1ee 用的是最新版本的SDK吗？WeiboSDK 这个JS 域 是最新几个版本的SDK 开始用的，如果是最新的0版本 那就删除插件 重新安装一边试一试

**Comment by roy1ee** [comment]
好的，谢谢。
