### ISSUE TITLE
使用登录出现程序退出

### ISSUE THREAD

**Issue by ViPenn** [iVanPan/cordova_weibo#4]
我在使用登录的时候出现了程序的退出，新浪那边的appkey  目前还是测试账户

**Comment by iVanPan** [comment]
app的签名要和新浪登记的一致，不然就会闪退

—

**Comment by ViPenn** [comment]
@iVanPan   就是说即使是测试账户，也需要完善在新浪注册的APP信息对吗?

**Comment by iVanPan** [comment]
信息不一定要完全，但至少签名要一致，这是sdk要求的，可以去看一下新浪微博sdk的使用文档

—

**Comment by ViPenn** [comment]
@iVanPan 恩恩好的 我看一下
