### ISSUE TITLE
weibo share iOS not working

### ISSUE THREAD

**Issue by zannet** [iVanPan/cordova_weibo#40]
iOS 下 weibo sso login 正常，android 平台 weibo share也正常，但 iOS下 weibo share 却没有任何反应，真机测试和 simulator 都不工作，没有报任何错，iOS的qq share 和 weixin share都正常

测试版本：
cordova-plugin-weibosdk: 0.5.8
cordova: 6.5.0
XCode: 8.2.1 
iOS Simulator: iPhone SE 10.2
iOS真机: iPhone 4s 8.3
操作系统: OS X EI Captain 10.11.6

**Comment by iVanPan** [comment]
@zannet  是不是图片太大了，或是URL 很长？ demo有测试过吗？

**Comment by iVanPan** [comment]
@zannet  我用 demo 测试了一下可以正常分享，测试环境是 iPhone 6 Plus iOS 10.3.1

**Comment by zannet** [comment]
@iVanPan 感谢回复，我再检查下

**Comment by zannet** [comment]
@iVanPan 经测试，是我分享内容的问题，感谢指出！

**Comment by zannet** [comment]
@iVanPan 有个问题，iOS下weibo share后，图片和文字都没了，只有一个链接是怎么回事

**Comment by iVanPan** [comment]
@zannet  微博搞的鬼，以前需要商务合作开通 LinkCard 才行，具体你去微博的 GitHub ，或是开发者中信问一下就好了

**Comment by zannet** [comment]
@iVanPan 了解了，感谢您这么及时的回复，祝好！

**Comment by goodsong** [comment]
@zannet 我碰到了一模一样的问题，请问你说的“分享内容的问题”是什么样的，要怎样改才能分享出去？谢谢！
