### ISSUE TITLE
How to share the text only

### ISSUE THREAD

**Issue by MGXu** [iVanPan/cordova_weibo#43]
How to share the text only

**Comment by iVanPan** [comment]
@MGXu  For Android,try to set title only, for iOS i don't implement share text function. if you need this function,PR is welcomed

**Comment by MGXu** [comment]
share success, but con't pubulish and show 10006 source paramter (appkey) is missing

**Comment by MGXu** [comment]
Where did you write to share the interface of the weibo, I need to be modified into a post interface
