### ISSUE TITLE
config.xml 怎么设置preference的value，我用了deep linking，但是仍然显示redirecturi mismatch <preference name="REDIRECTURI" value="http://192.168.1.17:8100/#/tabs" />

### ISSUE THREAD

**Issue by Chunmei12** [iVanPan/cordova_weibo#44]
import { Component } from '@angular/core';
import {IonicPage  } from 'ionic-angular';
import { ScreenComponent } from '../screens/screen.component';
import { SessionComponent } from '../session/session.component';
import { GamesComponent } from '../games/games.component';

@IonicPage({
  name:'tabs',
  segment:'tabsPage'
})
@Component({
  templateUrl: 'tabs.component.html'
})
export class TabsComponent {

  tab1Root = GamesComponent;
  tab2Root = ScreenComponent;
  tab3Root = SessionComponent;

  constructor() {

  }
}

**Comment by iVanPan** [comment]
...... REDIRECTURI 是指微博开放平台上面填写的的那个，http://192.168.1.17:8100 明显不对啊

**Comment by Chunmei12** [comment]
@iVanPan  谢谢啊
