### ISSUE TITLE
分享后  微博上面没有网页链接 

### ISSUE THREAD

**Issue by bmy411143785** [iVanPan/cordova_weibo#48]
分享后  微博上面没有网页链接 求解答

**Comment by iVanPan** [comment]
不好意思，你提供的信息太少，我也不知道 @bmy411143785

**Comment by bmy411143785** [comment]
不好意思，可以留个联系方式吗？我给你发相关信息

**Comment by iVanPan** [comment]
@bmy411143785  我 iOS 测试了一下没有问题，你是 Android 吗？ 用插件提供的 Demo 测试过没有？

**Comment by bmy411143785** [comment]
ios用测试demo点击提示Can't find variable: WeiboSDK，小白表示求指教，谢谢了

**Comment by iVanPan** [comment]
@bmy411143785  删除插件 重新安装最新版本

**Comment by bmy411143785** [comment]
下载ios sdk后按照api文档把libWeiboSDK复制到文件夹，打开xcode添加FrameWork文件后,文档说让定义appkey等常量，这个在哪里定义呢？后面的注册appkey和重写AppDelegate 的handleOpenURL和openURL的方法也都不懂。

**Comment by iVanPan** [comment]
https://github.com/iVanPan/cordova_weibo/blob/master/README_ZH.md 麻烦认真阅读，如果你不懂Cordova 的话 我也没有办法 @bmy411143785

**Comment by bmy411143785** [comment]
对不起我是不太懂Cordova，但是用的话也都会用。我按照您的步骤，下载安装后调用这个分享网页链接的方法,可以跳转到weibo客户端，发微博的窗口里面显示的是链接，可是发完微博查看的时候却变成了args .title的内容的普通文本,所以我很不解，不好意思，麻烦你了

**Comment by iVanPan** [comment]
这个应该是微博的问题，你可以安装微博官方提供的Demo，对比一下效果，或者搜索一下 Close 的 issue 看别人怎么解决的
