### ISSUE TITLE
微博分享不能回调onWbShareSuccess()等方法

### ISSUE THREAD

**Issue by zpliang94** [iVanPan/cordova_weibo#49]
demo可以回调接口WbShareCallback对应的方法的，导入插件后项目不能回调

**Comment by iVanPan** [comment]
能把信息提供完善吗？ 你这样说我也不知道什么情况的 @zpliang94

**Comment by zpliang94** [comment]
@iVanPan 使用shareToWeibo()时候，对应的标题，图片，URL地址是可以传到分享页面的，分享页面中点击分享按键后是微博用户是发出微博是分享成功的（notification有提示），不过在接口的WbShareCallback的回调方法onWbShareSuccess（）没有被调用，点击取消分享，方法onWbShareCancel（）也没有被调用，onWbShareFail（）也没有调用

**Comment by iVanPan** [comment]
@zpliang94  android 还是 iOS 插件是最新的吗？ 提供的demo 测试也是这样吗？

**Comment by zpliang94** [comment]
@iVanPan 是Android最新的插件，提供的demo测试时没有问题的，不过没有用命令行下载插件，是把对应的配置文件，js，java文件复制来的

**Comment by iVanPan** [comment]
最好用命令行安装 android sdk 的安装 依赖命令行，而且这几个版本的SDK 内部接口改动也比较大
