### ISSUE TITLE
sharefail

### ISSUE THREAD

**Issue by ViPenn** [iVanPan/cordova_weibo#5]
使用Android的时候进行分享，是不是也需要对APK签名进行配置？

**Comment by iVanPan** [comment]
必须和微博平台登记的一致，必须签名

—

**Comment by ViPenn** [comment]
但是我现在还没有开放完成，很多必填项都没法填，需要怎么来测试？

**Comment by iVanPan** [comment]
微博问题去微博开放平台查，看一下微博文档，微博官方Github 都有说明的

—

**Comment by ViPenn** [comment]
恩恩 好的，谢谢
