### ISSUE TITLE
分享成功，但是微博里没有分享的消息

### ISSUE THREAD

**Issue by hahajuzi** [iVanPan/cordova_weibo#50]
你好。我们的项目使用您的插件，分享到微博之后，会提示分享成功。但是IOS中会出现链接丢失现象。安卓会出现分享的内容在草稿箱的现象。联系微博开放平台，对方给的回复是  请使用最新的SDK。请问一下这个问题是由于SDK版本造成的吗？

**Comment by iVanPan** [comment]
是不是 连接太长了？ SDK 版本也是挺新的啊，你可以手动替换一下SDK 试试 @hahajuzi
