### ISSUE TITLE
用小米红米note4进行 monkey test的时候发生如下crash

### ISSUE THREAD

**Issue by moyiza-app** [iVanPan/cordova_weibo#53]
// java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sina.weibo.sdk.share.WbShareHandler.doResultIntent(android.content.Intent, com.sina.weibo.sdk.share.WbShareCallback)' on a null object reference

// 	at me.vanpan.weibosdk.WeiboSDKPlugin.onNewIntent(WeiboSDKPlugin.java:417)

// 	at org.apache.cordova.PluginManager.onNewIntent(PluginManager.java:327)

// 	at org.apache.cordova.CordovaWebViewImpl.onNewIntent(CordovaWebViewImpl.java:422)

// 	at org.apache.cordova.CordovaActivity.onNewIntent(CordovaActivity.java:257)

// 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1219)

// 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1231)

// 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2703)

// 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2715)

// 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2724)

// 	at android.app.ActivityThread.access$1800(ActivityThread.java:180)

// 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566)

// 	at android.os.Handler.dispatchMessage(Handler.java:111)

// 	at android.os.Looper.loop(Looper.java:207)

// 	at android.app.ActivityThread.main(ActivityThread.java:5791)

// 	at java.lang.reflect.Method.invoke(Native Method)

// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)

// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

//

**Comment by jasonz1987** [comment]
+1 闪退的次数很多。

**Comment by cxcxcxcx** [comment]
Google Play 的发布前测试也出现了这个问题：
FATAL EXCEPTION: main
Process: org.chinadialects.main, PID: 13382
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sina.weibo.sdk.share.WbShareHandler.doResultIntent(android.content.Intent, com.sina.weibo.sdk.share.WbShareCallback)' on a null object reference
	at me.vanpan.weibosdk.WeiboSDKPlugin.onNewIntent(WeiboSDKPlugin.java:417)
	at org.apache.cordova.PluginManager.onNewIntent(PluginManager.java:327)
	at org.apache.cordova.CordovaWebViewImpl.onNewIntent(CordovaWebViewImpl.java:422)
	at org.apache.cordova.CordovaActivity.onNewIntent(CordovaActivity.java:257)
...

**Comment by cxcxcxcx** [comment]
确认这个问题是 onNewIntent 中 call 了 WbShareHandler 导致的，在新版本中已经修复了
