### ISSUE TITLE
ios微博分享shareToWeibo中image,传不过去 

### ISSUE THREAD

**Issue by wuwenchang** [iVanPan/cordova_weibo#57]
cordova 版本v6.5.0
 xcode版本 v9.2，
cordova-plugin-weibosdk 版本0.6.0

# android 一切正常 ios图片带不过去，如果图片过大，ios跳转不过去
# 代码如下：
var args = {};
args.url = data.link;
args.title = data.title;
 args.description = data.desc;
args.image = data.imgUrl;
WeiboSDK.shareToWeibo( function () {
     taskCallback( taskname, scope );
}, function ( failReason ) {
     console.log(JSON.stringify(JSON.parse(failReason)));
}, args );

**Comment by iVanPan** [comment]
@wuwenchang  图片搞得小一点， 微博SDK 对图片大小有限制的
