### ISSUE TITLE
分享的时候只有一个页面链接

### ISSUE THREAD

**Issue by ViPenn** [iVanPan/cordova_weibo#6]
我分享成功后只有一个页面的链接，没有显示图片和文字，需要怎么修改？

**Comment by ViPenn** [comment]
我分享的是一个页面的链接，分享的内容里面包含图片和文字，但是只有一个链接 并没有显示图片和文字

**Comment by iVanPan** [comment]
@ViPenn  这是微博平台的问题 详情查看这里 https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20FAQ.md
<img width="893" alt="2015-11-12 22 02 15" src="https://cloud.githubusercontent.com/assets/1687276/11120165/1395cd26-8989-11e5-9c97-017af3ff0698.png">

**Comment by ViPenn** [comment]
关于这个linkcard 是需要向微博申请接入吗？如果不接入能使用吗？

**Comment by iVanPan** [comment]
@ViPenn  我觉得需要申请，具体的要求你可以去微博开放平台提问
