### ISSUE TITLE
分享成功没有图片

### ISSUE THREAD

**Issue by zhengjh** [iVanPan/cordova_weibo#7]
手机上有安装微博客户端，能分享成功，但是没有图片，调用如下
var args = {};
args.url = "http://www.baidu.com";
args.title = "Baidu";
args.description = "This is Baidu";
args.imageUrl = "https://www.baidu.com/img/bdlogo.png";
args.defaultText = "abcdefg";
YCWeibo.shareToWeibo(function () {
    alert("share success");
 }, function (failReason) {
    alert(failReason);
 }, args);

**Comment by iVanPan** [comment]
@zhengjh  看这里 https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20FAQ.md
<img width="928" alt="2015-11-26 16 08 18" src="https://cloud.githubusercontent.com/assets/1687276/11418133/f9febb28-9457-11e5-8a24-c7fc8d3e4536.png">

**Comment by zhengjh** [comment]
@iVanPan 看了下，如果不是想要这种linkcard的模式，而是链接
做为内容显示，而图片则是类似于发微博时上传图片的效果，如图，是否可实现？![32a40124c4a2e5d097fc8bd0874e5cbc](https://cloud.githubusercontent.com/assets/2022329/11418628/95008968-945c-11e5-9647-72b818162a39.png)

**Comment by iVanPan** [comment]
@zhengjh  这个要你自己查看微博文档接口了

**Comment by huawin03** [comment]
你给的Demo里面，Android下点击分享没有响应。然后我打到自己的项目里面也木成功，不知道是不是跟手机有关系，用的红米note。

**Comment by iVanPan** [comment]
@huawin03 你的签名正确嘛？跟手机Rom会有一定关系的

—

**Comment by zhengjh** [comment]
@iVanPan 好的，非常感谢呀~~~
