### ISSUE TITLE
如果手机上没有安装weibo客户端，会跳转到weibo登录页面么？安卓和IOS有区别么？

### ISSUE THREAD

**Issue by xiao1dian** [iVanPan/cordova_weibo#8]
我试了下好像不行

**Comment by iVanPan** [comment]
<img width="314" alt="2015-12-03 10 49 56" src="https://cloud.githubusercontent.com/assets/1687276/11550517/adbf34aa-99ab-11e5-9141-66880f904c89.png">

**Comment by xiao1dian** [comment]
安卓下也可以么，我用的安卓测试的 ，没有跳转报错了，有客户端的情况一切正常，回复这么快，谢谢 @iVanPan 
另外您的QQ那个plugin,我也有同样的问题，安卓上没客户端的情况下，也会跳转么？我这个问题可能在这个weibo的项目上问，不合适，请不要见怪。

**Comment by iVanPan** [comment]
@xiao1dian你的签名正确吗？我的测试环境是 nexus 5  Android 5.1.1 
![device-2015-12-03-110712](https://cloud.githubusercontent.com/assets/1687276/11550807/41532b02-99ae-11e5-82b6-006c61585a41.png)

**Comment by iVanPan** [comment]
@xiao1dian  有报错 看一下错误log，qq登录一般都是要客户端的，你可以看一下微博和QQ的 文档或是官方demo

**Comment by xiao1dian** [comment]
谢谢 @iVanPan 感谢您的回复，weibo我再测试下，至少得到了您的明确回复，安卓和IOS下都是没问题，可能是环境的问题。
至于qq，他们官方说安卓下必须有客户端，ios可以跳转到web 登陆界面，不过我看到有的app，安卓没有qq客户端也能跳转，这个让我很纳闷，也有可能他们不是直接用的qq官方的sdk，我在调研下，方便的时候您也可以试试。

微信的plugin，我还没来的及做，看到有个帖子，您也写了微信的plugin，如果方便能发给我一份看看么，我的邮箱xiao1dian@163.com.

再次感谢！

**Comment by iVanPan** [comment]
@xiao1dian  微信插件我已经很久没有更新了，你可以check 这个开源[项目](https://github.com/xu-li/cordova-plugin-wechat) 如果你想要不通过sdk来实现可以研究一下[openShare](https://github.com/100apps/openshare) 这个项目。关于qq跳转以前是可以的，但是要去申请权限
